# generated by fastapi-codegen:
#   filename:  optimizerapi/openapi/specification.yml
#   timestamp: 2026-02-02T15:38:44+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class ObjectivePars(Enum):
    result = 'result'
    expected_minimum = 'expected_minimum'


class Extras(BaseModel):
    objectivePars: Optional[ObjectivePars] = None
    graphFormat: Optional[str] = None
    experimentSuggestionCount: Optional[int] = None
    maxQuality: Optional[float] = None
    graphs: Optional[List[str]] = ['objective', 'convergence', 'pareto']


class Datum(BaseModel):
    xi: Optional[List[Union[str, float]]] = None
    yi: Optional[List[float]] = None


class Type(Enum):
    sum = 'sum'


class Constraint(BaseModel):
    type: Optional[Type] = None
    dimensions: List[float]
    value: float


class Type1(Enum):
    category = 'category'
    discrete = 'discrete'
    continuous = 'continuous'


class SpaceItem(BaseModel):
    type: Type1 = Field(
        ...,
        description='Type of the dimension. Can be category, discrete or continuous',
    )
    name: str
    from_: Optional[float] = Field(None, alias='from')
    to: Optional[float] = None
    categories: Optional[List[str]] = None


class Space(RootModel[List[SpaceItem]]):
    root: List[SpaceItem]


class Plot(BaseModel):
    id: Optional[str] = None
    plot: Optional[str] = Field(
        None, description='A base64 encoded png representation of the plot'
    )


class Model(BaseModel):
    expected_minimum: Optional[List[List[Union[str, float]]]] = None
    extras: Optional[Dict[str, Any]] = None


class Result1(BaseModel):
    expected_minimum: Optional[List[List[Union[str, float]]]] = None
    pickled: Optional[str] = None
    next: Optional[List[List[Union[str, float]]]] = None
    models: Optional[List[Model]] = None
    extras: Optional[Dict[str, Any]] = None


class Result(BaseModel):
    plots: Optional[List[Plot]] = None
    result: Optional[Result1] = None


class Error(BaseModel):
    message: Optional[str] = Field(
        None, description='Human readable description of the error'
    )
    error: Optional[str] = Field(
        None,
        description='Detailed error message as returned from the underlying routines',
    )


class Constraints(RootModel[List[Constraint]]):
    root: List[Constraint]


class OptimizerConfig(BaseModel):
    baseEstimator: Optional[str] = None
    acqFunc: Optional[str] = None
    initialPoints: Optional[int] = None
    kappa: Optional[float] = None
    xi: Optional[float] = None
    space: Optional[Space] = None
    constraints: Optional[Constraints] = None


class Experiment(BaseModel):
    extras: Optional[Extras] = Field(
        None, description='A plain JSON object that can contain arbitrary values'
    )
    data: List[Datum]
    optimizerConfig: OptimizerConfig
