version: '3.8'

services:
  api:
    restart: unless-stopped
    build:
      context: .
    command: python -m optimizerapi.server
    ports:
      - 9090:9090
    environment:
      - USE_WORKER=true
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=http://localhost:3000
      ## uncomment to enable authentication in the API specification
      #- PO_AUTH_URL=https://keycloak.browniebee.projects.alexandra.dk/realms/brownie-bee-dev/protocol/openid-connect/auth
  worker:
    restart: unless-stopped
    depends_on: 
      - redis
    build:
      context: .
    deploy:
      replicas: 10
    command: python -m optimizerapi.worker
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
  ui:
    image: ghcr.io/boostv/process-optimizer-frontend:1.6.3
    restart: unless-stopped
    ports:
      - 3000:80
    environment:
      - API_SERVER=http://api:9090/v1.0

volumes:
  redis-data: null
