[pytest]
filterwarnings =
    error
    ignore::UserWarning
    ignore:.*np\.int.*is a deprecated alias.*:DeprecationWarning
    ignore:Accessing jsonschema\.draft4_format_checker.*:DeprecationWarning
    ignore:jsonschema\.RefResolver is deprecated.*:DeprecationWarning
    ignore:jsonschema\.exceptions\.RefResolutionError is deprecated.*:DeprecationWarning