openapi: "3.0.0"

info:
  title: Process Optimizer API
  version: "1.0"
servers:
  - url: http://localhost:9090/v1.0

paths:
  /optimizer:
    get:
      description: Run optimizer with the specified parameters
      operationId: optimizer.run
      responses:
        '200':
          description: Result of running the optimizer with the specified parameters
          content:
            text/plain:
              schema:
                type: string
                example: hello
      parameters:
        - name: params
          in: query
          description: Parameters for the optimizer
          required: false
          schema:
            type: string
            example: "[1,2,3]"
        - name: Xi
          in: query
          description: "Xi value to be passed to ProcessOptimizer"
          required: false
          schema:
            type: number
            example: 0.01
        - name: yi
          in: query
          description: "yi value to be passed to ProcessOptimizer"
          required: false
          schema:
            type: number
            example: 1.0
        - name: kappa
          in: query
          description: "Kappa value to be passed to ProcessOptimizer"
          required: false
          schema:
            type: number
            example: 1.96
