openapi: "3.0.0"

info:
  title: Process Optimizer API
  version: "1.0"
servers:
  - url: http://localhost:9090/v1.0

paths:
  /optimizer:
    post:
      description: Run optimizer with the specified parameters
      operationId: optimizer.run
      responses:
        '200':
          description: Result of running the optimizer with the specified parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/result'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/experiment'

components:
  schemas:
    experiment:
      title: An experiment definition
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              xi:
                type: array
                items:
                  type: number
              yi:
                type: number
        optimizerConfig:
          type: object
          properties:
            baseEstimator:
              type: string
            acqFunc: 
              type: string
            initialPoints:
              type: integer
            kappa:
              type: number
            xi:
              type: number
            yi:
              type: number
            space:
              type: array
              items:
                type: object
                properties:
                  name: 
                    type: string
                  from:
                    type: number
                  to:
                    type: number
      required:
        - data
        - optimizerConfig
    result:
      title: Result of running optimizer on experiment
      type: object
      properties:
        plots:
          type: object
          properties:
            id:
              type: string
            plot:
              description: A base64 encoded png representation of the plot
              type: string
        result:
          type: object
          properties:
            next:
              type: array
              items:
                type: number