openapi: "3.0.0"

info:
  title: Process Optimizer API
  version: "1.0"
servers:
  - url: http://localhost:9090/v1.0

paths:
  /optimizer:
    post:
      description: Run optimizer with the specified parameters
      operationId: optimizer.run
      responses:
        '200':
          description: Result of running the optimizer with the specified parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/result'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/experiment'

components:
  schemas:
    experiment:
      title: An experiment definition
      type: object
      properties:
        extras:
          description: A plain JSON object that can contain arbitrary values
          type: object
        data:
          type: array
          items:
            type: object
            properties:
              xi:
                type: array
                items:
                  anyOf:
                    - type: string
                    - type: number
              yi:
                type: number
        optimizerConfig:
          type: object
          properties:
            baseEstimator:
              type: string
            acqFunc: 
              type: string
            initialPoints:
              type: integer
            kappa:
              type: number
            xi:
              type: number
            space:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                    description: Type of the dimension. Can be category, discrete or continuous
                  name: 
                    type: string
                  from:
                    type: number
                  to:
                    type: number
                  categories:
                    type: array
                    items:
                      type: string
                required:
                  - type
                  - name
                  
      required:
        - data
        - optimizerConfig
    result:
      title: Result of running optimizer on experiment
      type: object
      properties:
        plots:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              plot:
                description: A base64 encoded png representation of the plot
                type: string
        result:
          type: object
          properties:
            pickled:
              type: string
            next:
              type: array
              items:
                type: number
            extras:
              type: object